title: Amritansh Jain - Software Developer & AI Engineer
description: Personal portfolio and CV of Amritansh Jain, a Software Developer & AI Engineer with expertise in full-stack development and AI technologies.
url: https://amritansh22jain.github.io
baseurl: ""
permalink: pretty
